"""feed_template

Revision ID: 0a2bbd8a0d32
Revises: 6f331d6d7d77
Create Date: 2026-07-23 16:46:09.035545

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2bbd8a0d32'
down_revision: str | None = '6f331d6d7d77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_template',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fmt', sa.String(length=16), nullable=False),
    sa.Column('delimiter', sa.String(length=4), nullable=True),
    sa.Column('has_header', sa.Boolean(), nullable=False),
    sa.Column('fixed_fields', sa.JSON(), nullable=False),
    sa.Column('expected_columns', sa.JSON(), nullable=False),
    sa.Column('filename_glob', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_feed_template_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_template'))
    )
    with op.batch_alter_table('feed_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_template_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_template_tenant_id'))

    op.drop_table('feed_template')
    # ### end Alembic commands ###
