"""config lifecycle status

Revision ID: 1269e3a43857
Revises: d9f758ad6964
Create Date: 2026-07-23 14:43:09.312265

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1269e3a43857'
down_revision: str | None = 'd9f758ad6964'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lifecycle_status', sa.String(length=16), nullable=False, server_default='published'))

    with op.batch_alter_table('rule_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lifecycle_status', sa.String(length=16), nullable=False, server_default='published'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_set', schema=None) as batch_op:
        batch_op.drop_column('lifecycle_status')

    with op.batch_alter_table('mapping_config', schema=None) as batch_op:
        batch_op.drop_column('lifecycle_status')

    # ### end Alembic commands ###
