"""connectors: config, credential, sync_run

Revision ID: 13a354c74519
Revises: 985a07a52fa0
Create Date: 2026-07-23 12:31:24.447352

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a354c74519'
down_revision: str | None = '985a07a52fa0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_config',
    sa.Column('connector_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_ids', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_connector_config_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_config'))
    )
    with op.batch_alter_table('connector_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_config_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('connector_credential',
    sa.Column('connector_config_id', sa.Uuid(), nullable=False),
    sa.Column('secret_ref_name', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_config_id'], ['connector_config.id'], name=op.f('fk_connector_credential_connector_config_id_connector_config'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_connector_credential_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_credential')),
    sa.UniqueConstraint('connector_config_id', name=op.f('uq_connector_credential_connector_config_id'))
    )
    with op.batch_alter_table('connector_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_credential_connector_config_id'), ['connector_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_credential_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sync_run',
    sa.Column('connector_config_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_config_id'], ['connector_config.id'], name=op.f('fk_sync_run_connector_config_id_connector_config'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_sync_run_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_run'))
    )
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_run_connector_config_id'), ['connector_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_run_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_run_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sync_run_connector_config_id'))

    op.drop_table('sync_run')
    with op.batch_alter_table('connector_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_credential_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_connector_credential_connector_config_id'))

    op.drop_table('connector_credential')
    with op.batch_alter_table('connector_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_config_tenant_id'))

    op.drop_table('connector_config')
    # ### end Alembic commands ###
