"""customer workspace fields tier region status

Revision ID: 2a1855555c86
Revises: b20c2f0d850e
Create Date: 2026-07-23 16:19:49.089047

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1855555c86'
down_revision: str | None = 'b20c2f0d850e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=16), nullable=False, server_default='standard'))
        batch_op.add_column(sa.Column('region', sa.String(length=32), nullable=False, server_default='us'))
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False, server_default='active'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('region')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
