"""phase 0 tables

Revision ID: 6231cd7ca5d1
Revises:
Create Date: 2026-07-22 04:12:29.420995

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6231cd7ca5d1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenant_slug")),
    )
    op.create_table(
        "file",
        sa.Column("filename", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("storage_uri", sa.String(length=2048), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_file_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file")),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_file_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "mapping_config",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_signature", sa.String(length=512), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("layer", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_mapping_config_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapping_config")),
        sa.UniqueConstraint(
            "tenant_id", "file_signature", "version", name=op.f("uq_mapping_config_tenant_id")
        ),
    )
    with op.batch_alter_table("mapping_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mapping_config_file_signature"), ["file_signature"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mapping_config_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "rule_set",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("layer", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_rule_set_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_set")),
        sa.UniqueConstraint("tenant_id", "name", "version", name=op.f("uq_rule_set_tenant_id")),
    )
    with op.batch_alter_table("rule_set", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_set_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "taxonomy",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_taxonomy_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy")),
        sa.UniqueConstraint("tenant_id", "name", "version", name=op.f("uq_taxonomy_tenant_id")),
    )
    with op.batch_alter_table("taxonomy", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_taxonomy_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_user_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("tenant_id", "email", name=op.f("uq_user_tenant_id")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "job",
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["file.id"], name=op.f("fk_job_file_id_file"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_job_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_file_id"), ["file_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "output_row",
        sa.Column("source_file_id", sa.Uuid(), nullable=True),
        sa.Column("source_sheet", sa.String(length=255), nullable=True),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("mapping_config_version", sa.Integer(), nullable=True),
        sa.Column("rule_set_version", sa.Integer(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["file.id"],
            name=op.f("fk_output_row_source_file_id_file"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_output_row_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_output_row")),
    )
    with op.batch_alter_table("output_row", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_output_row_source_file_id"), ["source_file_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_output_row_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "rule",
        sa.Column("rule_set_id", sa.Uuid(), nullable=False),
        sa.Column("target_field", sa.String(length=255), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("condition", sa.JSON(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("layer", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_set_id"],
            ["rule_set.id"],
            name=op.f("fk_rule_rule_set_id_rule_set"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_rule_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule")),
    )
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_rule_set_id"), ["rule_set_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rule_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "sheet",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("sheet_name", sa.String(length=255), nullable=True),
        sa.Column("sheet_index", sa.Integer(), nullable=False),
        sa.Column("header_row_index", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["file.id"], name=op.f("fk_sheet_file_id_file"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_sheet_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sheet")),
    )
    with op.batch_alter_table("sheet", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sheet_file_id"), ["file_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sheet_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "taxonomy_alias",
        sa.Column("taxonomy_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=512), nullable=False),
        sa.Column("canonical_term", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["taxonomy_id"],
            ["taxonomy.id"],
            name=op.f("fk_taxonomy_alias_taxonomy_id_taxonomy"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_taxonomy_alias_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_alias")),
    )
    with op.batch_alter_table("taxonomy_alias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_taxonomy_alias_taxonomy_id"), ["taxonomy_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_taxonomy_alias_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "job_event",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_job_event_job_id_job"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_job_event_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_event")),
    )
    with op.batch_alter_table("job_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_event_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_event_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "profile",
        sa.Column("sheet_id", sa.Uuid(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("column_stats", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sheet_id"], ["sheet.id"], name=op.f("fk_profile_sheet_id_sheet"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_profile_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
        sa.UniqueConstraint("sheet_id", name=op.f("uq_profile_sheet_id")),
    )
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profile_sheet_id"), ["sheet_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_profile_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "suggestion",
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_suggestion_job_id_job"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_suggestion_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggestion")),
    )
    with op.batch_alter_table("suggestion", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_suggestion_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_suggestion_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "validation_flag",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_validation_flag_job_id_job"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["user.id"],
            name=op.f("fk_validation_flag_resolved_by_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_validation_flag_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_flag")),
    )
    with op.batch_alter_table("validation_flag", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_validation_flag_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_validation_flag_tenant_id"), ["tenant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("validation_flag", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_validation_flag_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_validation_flag_job_id"))

    op.drop_table("validation_flag")
    with op.batch_alter_table("suggestion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suggestion_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_suggestion_job_id"))

    op.drop_table("suggestion")
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_profile_sheet_id"))

    op.drop_table("profile")
    with op.batch_alter_table("job_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_event_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_job_event_job_id"))

    op.drop_table("job_event")
    with op.batch_alter_table("taxonomy_alias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_taxonomy_alias_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_taxonomy_alias_taxonomy_id"))

    op.drop_table("taxonomy_alias")
    with op.batch_alter_table("sheet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sheet_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_sheet_file_id"))

    op.drop_table("sheet")
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_rule_rule_set_id"))

    op.drop_table("rule")
    with op.batch_alter_table("output_row", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_output_row_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_output_row_source_file_id"))

    op.drop_table("output_row")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_job_file_id"))

    op.drop_table("job")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_tenant_id"))

    op.drop_table("user")
    with op.batch_alter_table("taxonomy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_taxonomy_tenant_id"))

    op.drop_table("taxonomy")
    with op.batch_alter_table("rule_set", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_set_tenant_id"))

    op.drop_table("rule_set")
    with op.batch_alter_table("mapping_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mapping_config_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_mapping_config_file_signature"))

    op.drop_table("mapping_config")
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_tenant_id"))

    op.drop_table("file")
    op.drop_table("tenant")
    # ### end Alembic commands ###
