"""tenant isolation_mode

Revision ID: 6f331d6d7d77
Revises: 2a1855555c86
Create Date: 2026-07-23 16:33:19.406994

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f331d6d7d77'
down_revision: str | None = '2a1855555c86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'isolation_mode',
                sa.String(length=16),
                nullable=False,
                server_default='pool',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('isolation_mode')

    # ### end Alembic commands ###
