"""tenant_settings reporting currency/tz/fx

Revision ID: 79b5c39e3a95
Revises: 13a354c74519
Create Date: 2026-07-23 13:32:30.907253

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b5c39e3a95'
down_revision: str | None = '13a354c74519'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('reporting_currency', sa.String(length=3), nullable=False),
    sa.Column('reporting_timezone', sa.String(length=64), nullable=False),
    sa.Column('fx_rates', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_settings_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_settings')),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_settings_tenant')
    )
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_settings_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_settings_tenant_id'))

    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
