"""add sheet.columns

Revision ID: 858faf4686b1
Revises: 6231cd7ca5d1
Create Date: 2026-07-22 10:57:43.477116

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "858faf4686b1"
down_revision: str | None = "6231cd7ca5d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sheet", schema=None) as batch_op:
        batch_op.add_column(sa.Column("columns", sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sheet", schema=None) as batch_op:
        batch_op.drop_column("columns")

    # ### end Alembic commands ###
