"""auth: user auth cols, session, secret_ref, idp config

Revision ID: a97d5c7c23e8
Revises: 858faf4686b1
Create Date: 2026-07-23 04:06:46.359379

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97d5c7c23e8'
down_revision: str | None = '858faf4686b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_provider_config',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('issuer', sa.String(length=1024), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('secret_ref_name', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_identity_provider_config_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_provider_config')),
    sa.UniqueConstraint('tenant_id', 'kind', name=op.f('uq_identity_provider_config_tenant_id'))
    )
    with op.batch_alter_table('identity_provider_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_provider_config_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('secret_ref',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_secret_ref_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_ref')),
    sa.UniqueConstraint('name', name=op.f('uq_secret_ref_name'))
    )
    with op.batch_alter_table('secret_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_ref_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('session',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_session_tenant_id_tenant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_session_token_hash'))
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_salt', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('password_salt')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_token_hash'))
        batch_op.drop_index(batch_op.f('ix_session_tenant_id'))

    op.drop_table('session')
    with op.batch_alter_table('secret_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_ref_tenant_id'))

    op.drop_table('secret_ref')
    with op.batch_alter_table('identity_provider_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_provider_config_tenant_id'))

    op.drop_table('identity_provider_config')
    # ### end Alembic commands ###
