"""runs actor created_by

Revision ID: b20c2f0d850e
Revises: 49e3ea7584aa
Create Date: 2026-07-23 15:45:09.973763

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20c2f0d850e'
down_revision: str | None = '49e3ea7584aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_job_created_by_user'), 'user', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sync_run_created_by_user'), 'user', ['created_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sync_run_created_by_user'), type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_job_created_by_user'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
