"""config authorship created_by

Revision ID: c705eaa06431
Revises: 79b5c39e3a95
Create Date: 2026-07-23 14:29:08.505944

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c705eaa06431'
down_revision: str | None = '79b5c39e3a95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_mapping_config_created_by_user'), 'user', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('rule_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rule_set_created_by_user'), 'user', ['created_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_set', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rule_set_created_by_user'), type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('mapping_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mapping_config_created_by_user'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
